FROM continuumio/miniconda3

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

COPY environment.yml /app/environment.yml
RUN conda env create -f environment.yml

SHELL ["/bin/bash", "-c"]

ENV PATH /opt/conda/envs/bcm1-wsl/bin:$PATH

COPY . /app

EXPOSE 8000

RUN echo "#!/bin/bash" > /app/entrypoint.sh && \
    echo "source activate bcm1-wsl && uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug" >> /app/entrypoint.sh && \
    chmod +x /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]