version: '3.9'

services:
  backend:
    image: saartank/synthetic-image-generator-backend:v0.2
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_S3_BUCKET_NAME=
      - AWS_S3_REGION=us-east-2
    networks:
      - my-network

  frontend:
    image: saartank/synthetic-image-generator-frontend:v0.2
    ports:
      - "3000:3000"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge